import type {GetServerSideProps} from "next";
import Head from "next/head";
import {ResponseData} from "src/constants";
import {IPost} from "src/service/PostService";
import styles from "../styles/Home.module.css";
import PostList from "src/components/PostList";

interface HomeProps {
    posts: ResponseData<IPost[]>;
}

const Home = (props: HomeProps) => {
    const {posts} = props;
    return (
        <div className={styles.container}>
            <Head>
                <title>Eco News</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <PostList posts={posts.data} />
            </main>
        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
    const data: ResponseData<IPost[]> = {
        message: "ok",
        code: 0,
        data: [
            {
                id: "01",
                status: "published",
                category: "politics",
                source: "Republic World",
                title: "Elon Musks parody account with blue tick tweets lyrics of Bhojpuri song",
                description:
                    "A verified account on Twitter has started tweeting in Hindi after making the profile look very similar to the real Tesla CEO Elon Musk's account",
                createdAt: "2022-11-05T07:52:12Z",
                updatedAt: "2022-11-05T07:52:12Z",
                content:
                    "Amid the ongoing Elon Musks Twitter acquisition drama, a verified account of the micro-blogging platform has started tweeting in Hindi after making the profile look very similar to the real Tesla CEO… [+1856 chars]",
            },
            {
                id: "02",
                status: "published",
                category: "business",
                source: "NDTV News",
                title: "Binance Helped Iranian Firms Trade $8 Billion Despite Sanctions: Report",
                description:
                    "Crypto giant Binance has processed Iranian transactions with a value of $8 billion since 2018 despite U.S. sanctions intended to cut Iran off from the global financial system, blockchain data show.",
                createdAt: "2022-11-05T07:52:12Z",
                updatedAt: "2022-11-05T07:52:12Z",
                content:
                    "Binance didn't answer detailed questions about the new transactions uncovered by Reuters.\r\nLondon: Crypto giant Binance has processed Iranian transactions with a value of $8 billion since 2018 despit… [+14490 chars]",
            },
            {
                id: "03",
                status: "published",
                category: "business",
                source: "RT",
                title: "Biden lashes out at Twitter and Musk",
                description:
                    "Twitter, which was recently acquired by Elon Musk, “spews lies all across the world,” US President Joe Biden has said Read Full Article at RT.com",
                createdAt: "2022-11-05T07:52:12Z",
                updatedAt: "2022-11-05T07:52:12Z",
                content:
                    "By acquiring Twitter last month, Elon Musk took charge of a social media platform that “spews lies all across the world,” US President Joe Biden said on Friday.\r\nThe comment came shortly after report… [+1639 chars]",
            },
            {
                id: "04",
                status: "published",
                category: "business",
                source: "Seeking Alpha",
                title: "Are The FANG Stocks Dead?",
                description:
                    "In the short-term, it seems that value investors, after more than a decade of underperformance, are finally taking a victory lap. Find out if FANG is dead.",
                createdAt: "2022-11-05T07:34:00Z",
                updatedAt: "2022-11-05T07:34:00Z",
                content:
                    "Ivanko_Brnjakovic/iStock Editorial via Getty Images\r\nAre the FANG stocks dead? Or, to be clear, are the MANNGMAT stocks dead? Of course, we are talking about the big technology heavyweights of Meta (… [+8220 chars]",
            },
            {
                id: "05",
                status: "published",
                category: "politics",
                source: "Republic World",
                title: "Elon Musks parody account with blue tick tweets lyrics of Bhojpuri song",
                description:
                    "A verified account on Twitter has started tweeting in Hindi after making the profile look very similar to the real Tesla CEO Elon Musk's account",
                createdAt: "",
                updatedAt: "",
                content:
                    "Amid the ongoing Elon Musks Twitter acquisition drama, a verified account of the micro-blogging platform has started tweeting in Hindi after making the profile look very similar to the real Tesla CEO… [+1856 chars]",
            },
            {
                id: "06",
                status: "published",
                category: "politics",
                source: "Seeking Alpha",
                title: "Weekly Commentary: Powell Building Credibility",
                description:
                    "Powell is an admirer of Paul Volcker’s fortitude, and he’s clearly drawing inspiration from the legendary Fed Chairman.",
                createdAt: "2022-11-05T07:24:00Z",
                updatedAt: "2022-11-05T07:24:00Z",
                content:
                    "Win McNamee\r\nThe guy sounds like a discerning traditional central banker. Powell is an admirer of Paul Volcker’s fortitude, and he’s clearly drawing inspiration from the legendary Fed Chairman. Marke… [+77018 chars]",
            },
            {
                id: "07",
                status: "published",
                category: "entertainment",
                source: "Yahoo Entertainment",
                title: "Twitter: Elon Musk blames 'activist groups' for earnings drop",
                description:
                    "Elon Musk, the new owner of Twitter, makes the accusation as the tech firm makes sweeping job cuts",
                createdAt: "2022-11-04T21:58:57Z",
                updatedAt: "2022-11-04T21:58:57Z",
                content:
                    'Mr Musk has been looking for ways to cut costs and make money in different ways from the platform\r\nElon Musk, the new owner of Twitter, has blamed "activist groups pressuring advertisers" for a "mass… [+3154 chars]',
            },

            {
                id: "09",
                status: "published",
                category: "health",
                source: "INSIDER",
                title: "Selena Gomez's former assistant says the singer didn't 'want to be alive' during her 2016 tour",
                description:
                    'Selena Gomez: My Mind & Me" shows the singer spiraling towards a "psychotic break," during which her friends say she was unrecognizable.',
                createdAt: "2022-11-04T04:05:00Z",
                updatedAt: "2022-11-04T04:05:00Z",
                content:
                    'Selena Gomez performs during her 2016 "Revival" tour in Sydney, Australia.Don Arnold/WireImage\r\n<ul><li>Selena Gomez\'s new documentary "My Mind &amp; Me" premiered on Apple TV+ on Friday.\r\n</li><li>T… [+3488 chars]',
            },
            {
                id: "10",
                status: "published",
                category: "politics",
                source: "Rolling Stone",
                title: "Kanye West Will Put Elon Musk’s ‘Free Speech’ Promise to the Test",
                description:
                    "The rapper continues to peddle antisemitism on Twitter. It could cost the new CEO — who happens to be his friend — a sizable fortune",
                createdAt: "2022-11-04T21:30:46Z",
                updatedAt: "2022-11-04T21:30:46Z",
                content:
                    "Elon Musk has owned Twitter for just one week — though in all the turmoil, it has felt like a lifetime. \r\nFrom the firing of top executives “for cause,” to the restriction of employee access to conte… [+6769 chars]",
            },
        ],
    };

    // const data = await PostService.getList()
    return {props: {posts: data}};
};

export default Home;
