import type { GetServerSideProps } from "next"
import Head from "next/head"
import { ResponseData } from "src/constants"
import PostService, { IPost } from "src/service/PostService"
import styles from "../styles/Home.module.css"
import PostList from "src/components/PostList"

interface HomeProps {
    posts: ResponseData<IPost[]>
}

const Home = (props: HomeProps) => {
    const { posts } = props
    return (
        <div className={styles.container}>
            <Head>
                <title>Eco News</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <PostList posts={posts.data} />
            </main>
        </div>
    )
}

export const getServerSideProps: GetServerSideProps = async context => {
    const data = await PostService.getList()
    return { props: { posts: data } }
}

export default Home
